services:
  postgres:
    image: postgres:15
    container_name: social_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - social_network

volumes:
  postgres_data:

networks:
  social_network:
    driver: bridge